version: '2'
services:
  mongo:
    image: mongo
    container_name: mongo
    command: --smallfiles
    environment:
      - MONGO_INITDB_DATABASE=app
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
  sjc_offers:
    image: sjc_offers
    container_name: sjc_offers
    build: .
    command: scrapy crawl offers
    depends_on:
      - mongo
